"""add_bundle_contexts_table

Revision ID: 1e6d992cdca0
Revises: 5fa905a9b817
Create Date: 2026-05-06 10:43:49.445162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e6d992cdca0'
down_revision = '5fa905a9b817'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bundle_contexts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('standard_id', sa.Integer(), nullable=False),
    sa.Column('passage_title', sa.String(length=200), nullable=False),
    sa.Column('passage_topic', sa.String(length=500), nullable=False),
    sa.Column('key_vocabulary', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bundle_contexts_id'), 'bundle_contexts', ['id'], unique=False)
    op.create_index(op.f('ix_bundle_contexts_standard_id'), 'bundle_contexts', ['standard_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bundle_contexts_standard_id'), table_name='bundle_contexts')
    op.drop_index(op.f('ix_bundle_contexts_id'), table_name='bundle_contexts')
    op.drop_table('bundle_contexts')
    # ### end Alembic commands ###
