"""Change social_snippets to JSONB

Revision ID: 5fa905a9b817
Revises: a60c0a81271c
Create Date: 2026-02-19 00:29:25.386259

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5fa905a9b817'
down_revision = 'a60c0a81271c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE products 
        ALTER COLUMN social_snippets TYPE JSONB 
        USING CASE 
            WHEN social_snippets IS NULL THEN NULL
            WHEN social_snippets = '' THEN NULL
            ELSE social_snippets::jsonb 
        END
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'social_snippets',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=True)
    # ### end Alembic commands ###
