"""Initial baseline migration

Revision ID: a60c0a81271c
Revises: 
Create Date: 2026-02-19 00:24:06.457406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a60c0a81271c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('locale', sa.Enum('US', name='locale'), nullable=False),
    sa.Column('file_type', sa.Enum('RAW_JSON', 'FINAL_JSON', 'METADATA_JSON', 'PDF', 'ZIP', 'THUMBNAIL', name='filetype'), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_artifacts_file_type'), 'file_artifacts', ['file_type'], unique=False)
    op.create_index(op.f('ix_file_artifacts_id'), 'file_artifacts', ['id'], unique=False)
    op.create_index('ix_file_artifacts_locale', 'file_artifacts', ['locale'], unique=False)
    op.create_index(op.f('ix_file_artifacts_product_id'), 'file_artifacts', ['product_id'], unique=False)
    op.create_index('ix_file_artifacts_product_type', 'file_artifacts', ['product_id', 'file_type'], unique=False)
    op.create_table('generation_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('standard_id', sa.Integer(), nullable=False),
    sa.Column('locale', sa.Enum('US', name='locale'), nullable=False),
    sa.Column('curriculum_board', sa.Enum('COMMON_CORE', name='curriculumboard'), nullable=False),
    sa.Column('grade_level', sa.Enum('6', '7', '8', name='gradelevel'), nullable=False),
    sa.Column('ela_standard_type', sa.Enum('RI', 'RL', name='elastandardtype'), nullable=False),
    sa.Column('ela_standard_code', sa.String(length=50), nullable=False),
    sa.Column('worldview_flag', sa.Enum('CHRISTIAN', 'NEUTRAL', name='worldviewflag'), nullable=False),
    sa.Column('job_type', sa.Enum('SINGLE_TEMPLATE', name='jobtype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=True),
    sa.Column('total_products', sa.Integer(), nullable=True),
    sa.Column('completed_products', sa.Integer(), nullable=True),
    sa.Column('failed_products', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_jobs_curriculum_board'), 'generation_jobs', ['curriculum_board'], unique=False)
    op.create_index(op.f('ix_generation_jobs_ela_standard_code'), 'generation_jobs', ['ela_standard_code'], unique=False)
    op.create_index(op.f('ix_generation_jobs_ela_standard_type'), 'generation_jobs', ['ela_standard_type'], unique=False)
    op.create_index('ix_generation_jobs_grade_ela', 'generation_jobs', ['grade_level', 'ela_standard_type'], unique=False)
    op.create_index(op.f('ix_generation_jobs_grade_level'), 'generation_jobs', ['grade_level'], unique=False)
    op.create_index(op.f('ix_generation_jobs_id'), 'generation_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_generation_jobs_job_type'), 'generation_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_generation_jobs_locale'), 'generation_jobs', ['locale'], unique=False)
    op.create_index('ix_generation_jobs_locale_curriculum', 'generation_jobs', ['locale', 'curriculum_board'], unique=False)
    op.create_index(op.f('ix_generation_jobs_standard_id'), 'generation_jobs', ['standard_id'], unique=False)
    op.create_index('ix_generation_jobs_standard_type', 'generation_jobs', ['standard_id', 'job_type'], unique=False)
    op.create_index(op.f('ix_generation_jobs_status'), 'generation_jobs', ['status'], unique=False)
    op.create_index('ix_generation_jobs_status_created', 'generation_jobs', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_generation_jobs_worldview_flag'), 'generation_jobs', ['worldview_flag'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('standard_id', sa.Integer(), nullable=False),
    sa.Column('generation_job_id', sa.Integer(), nullable=True),
    sa.Column('template_type', sa.Enum('BUNDLE_OVERVIEW', 'VOCABULARY_PACK', 'ANCHOR_READING_PASSAGE', 'READING_COMPREHENSION_QUESTIONS', 'SHORT_QUIZ', 'EXIT_TICKETS', name='templatetype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'GENERATED', 'FAILED', name='productstatus'), nullable=True),
    sa.Column('locale', sa.Enum('US', name='locale'), nullable=False),
    sa.Column('curriculum_board', sa.Enum('COMMON_CORE', name='curriculumboard'), nullable=False),
    sa.Column('grade_level', sa.Enum('6', '7', '8', name='gradelevel'), nullable=False),
    sa.Column('ela_standard_type', sa.Enum('RI', 'RL', name='elastandardtype'), nullable=False),
    sa.Column('ela_standard_code', sa.String(length=50), nullable=False),
    sa.Column('worldview_flag', sa.Enum('CHRISTIAN', 'NEUTRAL', name='worldviewflag'), nullable=False),
    sa.Column('is_christian_content', sa.Boolean(), nullable=True),
    sa.Column('seo_title', sa.String(length=255), nullable=True),
    sa.Column('seo_description', sa.String(length=500), nullable=True),
    sa.Column('internal_linking_block', sa.String(length=1000), nullable=True),
    sa.Column('social_snippets', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_curriculum_board'), 'products', ['curriculum_board'], unique=False)
    op.create_index(op.f('ix_products_ela_standard_code'), 'products', ['ela_standard_code'], unique=False)
    op.create_index(op.f('ix_products_ela_standard_type'), 'products', ['ela_standard_type'], unique=False)
    op.create_index('ix_products_generation_job_id', 'products', ['generation_job_id'], unique=False)
    op.create_index('ix_products_grade_ela', 'products', ['grade_level', 'ela_standard_type'], unique=False)
    op.create_index(op.f('ix_products_grade_level'), 'products', ['grade_level'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_is_christian_content'), 'products', ['is_christian_content'], unique=False)
    op.create_index(op.f('ix_products_locale'), 'products', ['locale'], unique=False)
    op.create_index(op.f('ix_products_standard_id'), 'products', ['standard_id'], unique=False)
    op.create_index('ix_products_standard_status', 'products', ['standard_id', 'status'], unique=False)
    op.create_index(op.f('ix_products_status'), 'products', ['status'], unique=False)
    op.create_index('ix_products_status_template', 'products', ['status', 'template_type'], unique=False)
    op.create_index(op.f('ix_products_template_type'), 'products', ['template_type'], unique=False)
    op.create_index('ix_products_worldview', 'products', ['worldview_flag', 'is_christian_content'], unique=False)
    op.create_index(op.f('ix_products_worldview_flag'), 'products', ['worldview_flag'], unique=False)
    op.create_table('standards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('locale', sa.Enum('US', name='locale'), nullable=False),
    sa.Column('curriculum_board', sa.Enum('COMMON_CORE', name='curriculumboard'), nullable=False),
    sa.Column('grade_level', sa.Enum('6', '7', '8', name='gradelevel'), nullable=False),
    sa.Column('ela_standard_type', sa.Enum('RI', 'RL', name='elastandardtype'), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_standards_code'), 'standards', ['code'], unique=False)
    op.create_index('ix_standards_code_unique', 'standards', ['locale', 'curriculum_board', 'code'], unique=True)
    op.create_index(op.f('ix_standards_curriculum_board'), 'standards', ['curriculum_board'], unique=False)
    op.create_index(op.f('ix_standards_ela_standard_type'), 'standards', ['ela_standard_type'], unique=False)
    op.create_index('ix_standards_grade_ela', 'standards', ['grade_level', 'ela_standard_type'], unique=False)
    op.create_index(op.f('ix_standards_grade_level'), 'standards', ['grade_level'], unique=False)
    op.create_index(op.f('ix_standards_id'), 'standards', ['id'], unique=False)
    op.create_index(op.f('ix_standards_locale'), 'standards', ['locale'], unique=False)
    op.create_index('ix_standards_locale_curriculum', 'standards', ['locale', 'curriculum_board'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_standards_locale_curriculum', table_name='standards')
    op.drop_index(op.f('ix_standards_locale'), table_name='standards')
    op.drop_index(op.f('ix_standards_id'), table_name='standards')
    op.drop_index(op.f('ix_standards_grade_level'), table_name='standards')
    op.drop_index('ix_standards_grade_ela', table_name='standards')
    op.drop_index(op.f('ix_standards_ela_standard_type'), table_name='standards')
    op.drop_index(op.f('ix_standards_curriculum_board'), table_name='standards')
    op.drop_index('ix_standards_code_unique', table_name='standards')
    op.drop_index(op.f('ix_standards_code'), table_name='standards')
    op.drop_table('standards')
    op.drop_index(op.f('ix_products_worldview_flag'), table_name='products')
    op.drop_index('ix_products_worldview', table_name='products')
    op.drop_index(op.f('ix_products_template_type'), table_name='products')
    op.drop_index('ix_products_status_template', table_name='products')
    op.drop_index(op.f('ix_products_status'), table_name='products')
    op.drop_index('ix_products_standard_status', table_name='products')
    op.drop_index(op.f('ix_products_standard_id'), table_name='products')
    op.drop_index(op.f('ix_products_locale'), table_name='products')
    op.drop_index(op.f('ix_products_is_christian_content'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_grade_level'), table_name='products')
    op.drop_index('ix_products_grade_ela', table_name='products')
    op.drop_index('ix_products_generation_job_id', table_name='products')
    op.drop_index(op.f('ix_products_ela_standard_type'), table_name='products')
    op.drop_index(op.f('ix_products_ela_standard_code'), table_name='products')
    op.drop_index(op.f('ix_products_curriculum_board'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_generation_jobs_worldview_flag'), table_name='generation_jobs')
    op.drop_index('ix_generation_jobs_status_created', table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_status'), table_name='generation_jobs')
    op.drop_index('ix_generation_jobs_standard_type', table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_standard_id'), table_name='generation_jobs')
    op.drop_index('ix_generation_jobs_locale_curriculum', table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_locale'), table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_job_type'), table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_id'), table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_grade_level'), table_name='generation_jobs')
    op.drop_index('ix_generation_jobs_grade_ela', table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_ela_standard_type'), table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_ela_standard_code'), table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_curriculum_board'), table_name='generation_jobs')
    op.drop_table('generation_jobs')
    op.drop_index('ix_file_artifacts_product_type', table_name='file_artifacts')
    op.drop_index(op.f('ix_file_artifacts_product_id'), table_name='file_artifacts')
    op.drop_index('ix_file_artifacts_locale', table_name='file_artifacts')
    op.drop_index(op.f('ix_file_artifacts_id'), table_name='file_artifacts')
    op.drop_index(op.f('ix_file_artifacts_file_type'), table_name='file_artifacts')
    op.drop_table('file_artifacts')
    # ### end Alembic commands ###
